name: Release

on:
    push:
        branches: [master]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
    contents: write
    pull-requests: write
    id-token: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: oven-sh/setup-bun@v2
            - run: bun install --frozen-lockfile
            - uses: changesets/action@v1
              with:
                  publish: bun run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
